### ISSUE TITLE
Problem generating PCAs in supervised pipeline

### ISSUE THREAD

**Issue by patritb** [mlfpm/deepof#43] opened 2024-06-08 11:52 UTC
Hi! First of all, thank you for this very promising software and your very comprehensive tutorials.

I'm trying to analyze some videos labeled with 14 points. I have a total of 16 videos, 4 for each experimental condition (4 in total). They are top-down views of a single animal each, five minutes long. I've generated Gantt plots and trait enrichment plots, and they look great and make sense. However, when I try to generate PCAs, I encounter this message:

Traceback (most recent call last):
  File "C:\Users\patri\anaconda3\envs\deepof\lib\site-packages\scipy\stats\_kde.py", line 226, in __init__
    self.set_bandwidth(bw_method=bw_method)
  File "C:\Users\patri\anaconda3\envs\deepof\lib\site-packages\scipy\stats\_kde.py", line 574, in set_bandwidth
    self._compute_covariance()
  File "C:\Users\patri\anaconda3\envs\deepof\lib\site-packages\scipy\stats\_kde.py", line 586, in _compute_covariance
    self._data_cho_cov = linalg.cholesky(self._data_covariance,
  File "C:\Users\patri\anaconda3\envs\deepof\lib\site-packages\scipy\linalg\_decomp_cholesky.py", line 88, in cholesky
    c, lower = _cholesky(a, lower=lower, overwrite_a=overwrite_a, clean=True,
  File "C:\Users\patri\anaconda3\envs\deepof\lib\site-packages\scipy\linalg\_decomp_cholesky.py", line 36, in _cholesky
    raise LinAlgError("%d-th leading minor of the array is not positive "
numpy.linalg.LinAlgError: 2-th leading minor of the array is not positive definite

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\patri\Desktop\MN1_IA\Analisis con DeepOF\Script3_Supervised_DeepOF.py", line 100, in <module>
    deepof.visuals.plot_embeddings(
  File "C:\Users\patri\anaconda3\envs\deepof\lib\site-packages\deepof\visuals.py", line 1399, in plot_embeddings
    sns.kdeplot(
  File "C:\Users\patri\anaconda3\envs\deepof\lib\site-packages\seaborn\_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "C:\Users\patri\anaconda3\envs\deepof\lib\site-packages\seaborn\distributions.py", line 1783, in kdeplot
    p.plot_bivariate_density(
  File "C:\Users\patri\anaconda3\envs\deepof\lib\site-packages\seaborn\distributions.py", line 1111, in plot_bivariate_density      
    density, support = estimator(*observations, weights=weights)
  File "C:\Users\patri\anaconda3\envs\deepof\lib\site-packages\seaborn\_statistics.py", line 189, in __call__
    return self._eval_bivariate(x1, x2, weights)
  File "C:\Users\patri\anaconda3\envs\deepof\lib\site-packages\seaborn\_statistics.py", line 164, in _eval_bivariate
    support = self.define_support(x1, x2, cache=False)
  File "C:\Users\patri\anaconda3\envs\deepof\lib\site-packages\seaborn\_statistics.py", line 121, in define_support
    support = self._define_support_bivariate(x1, x2, weights)
  File "C:\Users\patri\anaconda3\envs\deepof\lib\site-packages\seaborn\_statistics.py", line 104, in _define_support_bivariate      
    kde = self._fit([x1, x2], weights)
  File "C:\Users\patri\anaconda3\envs\deepof\lib\site-packages\seaborn\_statistics.py", line 137, in _fit
    kde = stats.gaussian_kde(fit_data, **fit_kws)
  File "C:\Users\patri\anaconda3\envs\deepof\lib\site-packages\scipy\stats\_kde.py", line 235, in __init__
    raise linalg.LinAlgError(msg) from e
numpy.linalg.LinAlgError: The data appears to lie in a lower-dimensional subspace of the space in which it is expressed. This has resulted in a singular data covariance matrix, which cannot be treated using the algorithms implemented in `gaussian_kde`. Consider performing principle component analysis / dimensionality reduction and using `gaussian_kde` with the transformed data.

The code I'm using is the same you posted in the tutorial:

deepof.visuals.plot_embeddings(
    my_deepof_project,
    supervised_annotations=supervised_annotation,
    ax=ax1,

)

I'm guessing that it probably has something to do with the fact that in my dataset there's only one animal per video instead of two? I'm sure I'm missing something, and there's probably a simple way to solve this problem from within the supervised pipeline script rather than resorting to data transformations. I've checked the API and tried several things but I keep getting the same error.

Thanks in advance for your help!

**Comment by NoCreativeIdeaForGoodUserName** [comment] 2024-06-10 12:04
Dear Patritb,

Thank you for your interest in DeepOF. I cannot give you a definite answer what is going wrong right now. However, as the error happens within the sns.kdeplot function and you have a relatively low number of shorter videos with multiple different experimental conditions, it could be that the function simply fails to do a proper estimate of the probability density function based on this data set. 

If you would be willing to share your data, I can offer to try to reproduce your error and give you a more exact answer regarding what is going wrong and if there is a workaround. 

My work e-mail is: patrick_schlegel@psych.mpg.de

Best regards,
Patrick

**Comment by patritb** [comment] 2024-06-10 14:04
Hi Patrick,

Thank you so much for your quick response! I'm re-running the analysis with more videos (110 in total, 26-27 per experimental condition) to see if that resolves the issue. I'll get back to you with the results. If the problem persists, I'd be happy to share the data with you so you can take a closer look.

Thanks again!

**Comment by NoCreativeIdeaForGoodUserName** [comment] 2024-06-10 15:24
Dear Patritb,

That should be a sufficient number. If you like, you can share the small initial sample of the dataset with me even if the larger set works out perfectly for you. After all it would probably be nice for the user to at least get a more specific error message.

Best regards,
Patrick

**Comment by patritb** [comment] 2024-06-11 11:12
Hi Patrick,

The initial sample of the dataset was indeed the problem, so thank you for pointing that out! Now, the PCAs are being generated. Of course, I'll send you the original dataset via e-mail so you can check out the problem and refine the error message.

Thanks!

**Comment by NoCreativeIdeaForGoodUserName** [comment] 2024-06-11 12:11
Thank you. I will keep this issue open until I had a look at your sample. I will also edit my previous post here to remove my e-mail address later today (because I don't want it to be caught by data scrapers in the future).

**Comment by NoCreativeIdeaForGoodUserName** [comment] 2024-06-14 14:10
I added some code that ensures that the rank of the point matrix based on each group combination is at least 2. If this is not the case, sns.kdeplot is skipped and an error message is produced:

> Error! Failed to plot continuous probability density curve!
> Some Experimental condition combinations do not span at least two dimensions!
> This Error may happen due to an insufficient amount of data.

This fix will be included starting with deepof version 0.7. I will close the issue as soon as this version is released.

**Comment by NoCreativeIdeaForGoodUserName** [comment] 2024-08-16 23:19
Deepof 0.7 is released and the fix is included. I close this issue.

**Closed by NoCreativeIdeaForGoodUserName** 2024-08-16 23:19 UTC
